"""add wishlist, cart, address, ratings

Revision ID: 60636a30a2c3
Revises: 
Create Date: 2025-06-11 13:49:40.014509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60636a30a2c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('user_pkey'))
    )
    # ### end Alembic commands ###
